-- Django CRUD Lab database reference script.
--
-- Normal Django setup should still use:
--   python manage.py migrate
--
-- This script is useful for inspecting the Postgres table shape or bootstrapping
-- a standalone demo database:
--   createdb django_crud
--   psql -d django_crud -f database/init.sql

BEGIN;

CREATE TABLE IF NOT EXISTS "tasks_task" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(120) NOT NULL,
    "description" text NOT NULL,
    "status" varchar(20) NOT NULL,
    "priority" varchar(10) NOT NULL,
    "due_date" date NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

INSERT INTO "tasks_task" (
    "title",
    "description",
    "status",
    "priority",
    "due_date",
    "created_at",
    "updated_at"
)
SELECT
    seed."title",
    seed."description",
    seed."status",
    seed."priority",
    seed."due_date"::date,
    now(),
    now()
FROM (
    VALUES
        (
            'Learn Django models',
            'Define the Task table with model fields and migrations.',
            'done',
            'high',
            '2026-06-22'
        ),
        (
            'Compare HTMX and SvelteKit',
            'Use the same CRUD app to compare server-rendered and API-driven frontends.',
            'in_progress',
            'high',
            '2026-06-24'
        ),
        (
            'Practice API endpoints',
            'Call GET, POST, PATCH, and DELETE routes from the SvelteKit frontend.',
            'todo',
            'medium',
            '2026-06-26'
        )
) AS seed("title", "description", "status", "priority", "due_date")
WHERE NOT EXISTS (
    SELECT 1
    FROM "tasks_task"
    WHERE "tasks_task"."title" = seed."title"
);

COMMIT;